AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  YourFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Events:
        UserProfile:
          Type: Api
          Properties:
            Path: /users/profile/{username}
            Method: get
        UserNotifications:
          Type: Api
          Properties:
            Path: /users/notifications
            Method: get
        UserDatasets:
          Type: Api
          Properties:
            Path: /users/datasets
            Method: get
        UserC4Ds:
          Type: Api
          Properties:
            Path: /users/c4ds
            Method: get