AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  YourFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Events:
        LoginRequest:
          Type: Api
          Properties:
            Path: /login
            Method: post
        RegisterRequest:
          Type: Api
          Properties:
            Path: /register
            Method: post
        ProfileRequest:
          Type: Api
          Properties:
            Path: /profile/{username+}
            Method: get
      Environment:
        Variables:
          CLIENT_SECRET: CLIENTHERE
          KEYCLOAK_ADMIN_USERNAME: USERNAME
          KEYCLOAK_ADMIN_PASSWORD: PASSWORD
          KEYCLOAK_REALM: master
    Metadata:
      SamResourceId: YourFunction