Parameters:
  EcrImageUri:
    Description: ECR image URI of ddai-api-user
    Type: String

Resources:
  DDAIApiUserLambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      FunctionName: ddai-api-user
      Role: arn:aws:iam::381492109137:role/service-role/ddai-api-user-role-h5u16x88
      Code:
        ImageUri: !Ref EcrImageUri
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 2
      VpcConfig:
        SecurityGroupIds:
          - sg-0cccd601e3bbf2fa1
          - sg-026a1e595910d0beb
          - sg-01f9b8805a7f5b071
          - sg-02310a134ffb32adb
        SubnetIds:
          - subnet-0d2c8172d8a85a69f
          - subnet-0e05f00d80886caae
          - subnet-03b2a57b732842a2d

